### PR TITLE
39 create UI for signup and login

### PR DESCRIPTION
**Pull request by oonasaksman**
## Describe your changes

Implemented sign up and register pages UI's and changes file names.

## Checklist before requesting a review

-   [x] I have performed a self-review of my code
-   [x] I have commented my code, particularly in hard-to-understand areas
-   [ ] I have added thorough tests

### CODE REVIEW

**Comment by Marakke** [comment]
Looks good! Maybe the component names could be changed. I don't personally like numbers in them.

Maybe <UsernameRegistration /> and <UserInfoRegistration />

**Comment by Marakke** [comment]
@oonasaksman you haven't assigned any reviewers. Is the branch ready?

**Review by vrindavj — APPROVED** [review]
The file name changes are also included. Great job😊

**Review by Marakke — APPROVED** [review]
Good job! Next let's add Routing to these, but we can do that in a separate pull request :)

**Pull request merged**
