### PR TITLE
Backend mvp

### LINKED ISSUE #13: Simple multi-choice poll creation - Backend
Simple polls (basic question type) can be created and data must be able to be sent to the frontend
Poll must have a name.

### LINKED ISSUE #51: Answering multi-choice questions - Backend

### LINKED ISSUE #52: Fetching multi-choice poll public view - Backend

### PR DESCRIPTION
**Pull request by joonashalinen**
## Describe your changes

The backend is now at a stage where you can create, fetch and answer polls as shown in the api documentation. The api is documented and most methods have some kind of unit tests.

## Checklist before requesting a review

-   [x] I have performed a self-review of my code
-   [x] I have commented my code, particularly in hard-to-understand areas
-   [x] I have added thorough tests

### CODE REVIEW

**Comment by Jontzii** [comment]
@joonashalinen, I think the PR is now OK to merge, but there are a couple of things I forgot to specify before that should be considered when writing more code. I have listed the items below and in CODING_GUIDELINES.md in the backend folder. I also changed those things myself as it was me who forgot to specify those things before and I didn't think it would be fair to make you do that kind of extra work for my mistake :) (I didn't fix all of those but created tickets for those issues)

These are the things I noticed (in no particular order):
- Don't use `var`, use `const` and `let` instead => I changed these. They will cause errors in the future when I add Eslint to the CI
- Always write tests in TypeScript if the source you are testing is TypeScript
  - I changed these for now (was kind of a lot of work😅)
  - I removed some tests that became unnecessary with this change
- Try to define more interfaces with clearer names and define them outside of the function that uses it
  - I exported at least most of the interface definitions that were made in the functions, to separate files
  - As a result of this, there **are** ambiguous interfaces in different files that should be looked at => I created a ticket for this
- This links to the previous one but try to minimize the use of `any` as it makes it pretty hard to understand the code/types when reading as outsider
  - In some cases such as error catching, I would prefer `unknown` over `any`
- You used console.log in some place, use the `Logger` from `utils` instead as it uses the Winston logger
- Use arrow functions where possible => consistent coding style between front- and backend

**Review by Jontzii — APPROVED** [review]
Approved with my above comment

**Comment by Jontzii** [comment]
FYI, I created tickets #56 #57 #58 #59 from things that I noticed but did not fix.

**Review by nataajj — APPROVED** [review]
this code is a better version than we currently have on production. Jontzi's comments (and fixes) are good. There is a small fundamental thing with answer anonymity that we need to discuss but merge this now and create tickets after if we decide it is needed.

**Pull request merged**
