### PR TITLE
refactor backend classes

### LINKED ISSUE #57: Refactor ambiguous interfaces from backend
After the initial backend MVP by @joonashalinen and the changes made to that by @Jontzii, the backend contains some ambiguous interfaces.

- [ ] Find these duplicates and remove them
- [ ] Rename the old unclear ones in a better way
- [ ] Define types for the remaining `any` types

### PR DESCRIPTION
**Pull request by joonashalinen**
split long functions to smaller, use more interfaces and aim to eliminate the use of any

## Describe your changes

1. Split long methods into smaller ones. 
2. Almost completely eliminated the use of any. There are two spots where any is still left. The first one is in pollController.ts and the second one in Poll.test.ts. The any in pollController is difficult to remove and the one in Poll.test.ts is not done by me.
3. Made the code use defined interfaces. Made new interfaces where they were missing.

## Checklist before requesting a review

-   [x] I have performed a self-review of my code
-   [x] I have commented my code, particularly in hard-to-understand areas
-   [ ] I have added thorough tests

### CODE REVIEW

**Comment by Jontzii** [comment]
Fixed the any in the Poll.test.ts -file

**Comment by Jontzii** [comment]
I was thinking if `any` in the `PollController` could be replaced with a switch or something?🤔

I was thinking something like this:
```
switch (method) {
    case 'createPoll':
        poll = await service.createPoll(req.body);
        break;
    case 'answerPoll':
        poll = await service.answerPoll(req.body);
        break;
    case 'getPollWithPublicId':
        poll = await service.getPollWithPublicId(req.body);
        break;
    case 'getPollWithPrivateId':
        poll = await service.getPollWithPrivateId(req.body);
        break;
    default:
        throw new Error('Incorrect method name');
}
```

**Review by Jontzii — DISMISSED** [review]
Looks good to me, the any in PollController can be fixed later :)

**Review by nataajj — APPROVED** [review]

**Comment by Jontzii** [comment]
Rebased to dev manually, found issue in one test and fixed issue with Jest fail

**Review by Jontzii — APPROVED** [review]

**Review by nataajj — APPROVED** [review]

**Pull request merged**
