### PR TITLE
44 admin user creation

### LINKED ISSUE #44: Admin user creation
Create UI for admin to see list of all user accounts.Also, Admin should be able to mark other a user account as another admin (ie assign admin rights to normal users)

- First admin does not need to be created.

### PR DESCRIPTION
**Pull request by Marakke**
## Describe your changes

Added basic Admin View layout and user listing template.

## Checklist before requesting a review

-   [x] I have performed a self-review of my code
-   [x] I have commented my code, particularly in hard-to-understand areas
-   [ ] I have added thorough tests

### CODE REVIEW

**Review by vrindavj — DISMISSED** [review]
The UI looks good.
I guess the default styling of textfield/links can be fixed later..Rest all seems great!!
Nice job👍🏻

**Review by JeToKo — DISMISSED** [review]
Everything looks OK

**Review by vrindavj — APPROVED** [review]
Approved

**Review by oonasaksman — DISMISSED** [review]

**Comment by Marakke** [comment]
Need approvals again @JeToKo @vrindavj @oonasaksman

**Review by vrindavj — APPROVED** [review]
Approved

**Review by JeToKo — APPROVED** [review]
Good job.

**Pull request merged**
